<a href="https://colab.research.google.com/github/hadwin-357/ProteinMPNN_breakdown/blob/main/model_utils_function_3_gather_edge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#test model utils function
# graphic neuro network function
# gether edge
'''
inputs:  edges (B, N, N, C) # Batch, node, node, feature  # this is a fully connected, self looped GNN
neighbor_idx (B, N, K) # Batch, node, index for k-nearest neighbors

Return:
Based on N (node index), K(neighbor, index)to gather according features from edges
'''

In [5]:
#Test functions 1: gather_edge
def gather_edges(edges, neighbor_idx):
  # Features [B,N,N,C] at Neighbor indices [B,N,K] => Neighbor features [B,N,K,C]
  neighbor=neighbor_idx.unsqueeze(-1).expand(-1, -1, -1, edges.size(-1))# [B,N,K] => Neighbor features [B,N,K,C]
  edge_features=torch.gather(edges, 2, neighbor)
  return edge_features

In [1]:
import torch

# Create random edge features
edges = torch.randn(2, 3, 3, 2)  # Batch size = 2, Number of nodes = 3, Number of features = 2

# Create random neighbor indices
neighbor_idx = torch.randint(0, 3, (2, 3, 2))  # Batch size = 2, Number of nodes = 3, Number of neighbors = 2


In [3]:
neighbor_idx[0,0,:] # batch 0, node 0 according two neighbors (1, 1), In reality, the two neighbors should be different

tensor([1, 1])

In [6]:
# Gather edge features
edge_features = gather_edges(edges, neighbor_idx)

print("Shape of edge_features:", edge_features.shape)
print("Edge features tensor:")
print(edge_features)


Shape of edge_features: torch.Size([2, 3, 2, 2])
Edge features tensor:
tensor([[[[-0.4292,  1.4102],
          [-0.4292,  1.4102]],

         [[ 1.5641, -0.5656],
          [-1.0257,  1.2498]],

         [[ 1.1425, -1.6480],
          [ 1.3194, -0.9216]]],


        [[[-1.5294, -1.2688],
          [ 0.0638, -0.0996]],

         [[-0.3082, -1.3900],
          [-0.3082, -1.3900]],

         [[ 1.7021, -0.7098],
          [ 1.4389, -0.2297]]]])


In [13]:
edges[0,0,1,:] # edge feature for batch 0, node 0-node 1 edge

tensor([-0.4292,  1.4102])

In [12]:
edge_features[0,0,1,:]  # edge feature for batch 0, node 0-#neighour 1 edge  # both neighbors are 1

tensor([-0.4292,  1.4102])